### ISSUE TITLE
[BOJ] 10844 출력 관련 질문

### ISSUE THREAD

**Issue by rbgus2002** [algorithmSSU/yoonsuKim#1]
궁금한 점이 생겨서 이슈 남깁니당.
문제의 조건을 보시면 10^9으로 나눈 나머지를 출력하라고 나와있습니다! 물론 조건에 맞춰서 잘 출력하셨더라고요.
저도 윤수님이랑 같은 로직으로 자바 언어 사용해서 구현했는데, 출력할 때는 물론 loop 돌며 bottom-up 방식으로 배열에 값 저장할 때도 10^9로 매번 나눠서 저장하지 않으면 틀렸다고 나오더라구요 ㅠ
1. 파이썬은 dynamic binding으로 알고 있는데 변수에 정수 저장하면 어떤 타입이 되는건가요?
2.  사실 그냥 구글링해보면 되긴 하지만 이런 부분까지 고려하시면서 푸셨는 지 윤수님 생각이 궁금합니다! 저는 매번 왜 나눠줘야 하는 지, 어떤 부분에서 매번 나누어 주어야겠다고 캐치를 했어야 했는 지 잘 모르겠어서 여쭤봐요.....!

**Comment by ing03201** [comment]
저는 규칙이 어떻게 될까 하고 생각한 이후에 그 예시에 대한 것을 5개 정도 써서 다시 봅니다
읽어보니 자료형 문제인거같은데 저도 한번 디버깅해볼께요
